version: '3'

services:
    phptripncity:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - tripncity
    nginxtripncity:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8180:80
        networks:
            - tripncity
    dbserver:
        image: mariadb
        # command: --default-authentication-plugin=mysql_native_password 
        volumes:
            - "./database-data:/var/lib/mysql"
            - "./database-bridge:/home"
        environment:
            MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MYSQL_DATABASE}
            MARIADB_USER: ${MYSQL_USER}
            MARIADB_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - tripncity
    phpmyadmin:
        image: phpmyadmin
        ports:
        - 8181:80
        environment:
            - PMA_HOST=dbserver
        networks:
            - tripncity
networks:
    tripncity:
